name: tcc-utin-natality-2024
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - jupyter
  - notebook
  - nbconvert
  - ipython
  - numpy
  - pandas
  - pyarrow
  - requests
  - matplotlib
  - scikit-learn
  - statsmodels
  - xgboost
  - openpyxl
  - graphviz
  - pip
  - pip:
      - zipfile-deflate64>=0.2.0
